# tb-cpp-compatibility: recreates Terminal-Bench original-tasks/cpp-compatibility (Apache-2.0) on the overlay runner.
# Generated by out/h50/gen_setup.py from the task's files, byte for byte.
mkdir -p /app
base64 -d <<'EOF' > /app/sum_array.h
I2luY2x1ZGUgPGFycmF5PgoKdGVtcGxhdGUgPHR5cGVuYW1lIFQsIHN0ZDo6c2l6ZV90IE4+CmNv
bnN0ZXhwciBUIHN1bV9hcnJheShjb25zdCBzdGQ6OmFycmF5PFQsIE4+ICZhcnIpCnsKICAgIFQg
c3VtID0gMDsKICAgIGZvciAoc3RkOjpzaXplX3QgaSA9IDA7IGkgPCBOOyArK2kpCiAgICB7CiAg
ICAgICAgc3VtICs9IGFycltpXTsKICAgIH0KICAgIHJldHVybiBzdW07Cn0=
EOF
