# tb-csv-to-parquet: recreates Terminal-Bench original-tasks/csv-to-parquet (Apache-2.0) on the overlay runner.
# Generated by out/h50/gen_setup.py from the task's files, byte for byte.
mkdir -p /app
base64 -d <<'EOF' > /app/data.csv
bmFtZSxhZ2UsY2l0eQpKb2huLDI1LE5ldyBZb3JrCkFsaWNlLDMwLFNhbiBGcmFuY2lzY28KQm9i
LDM1LENoaWNhZ28KRW1tYSwyOCxCb3N0b24KRGF2aWQsMzMsU2VhdHRsZSA=
EOF
