# tb-log-summary: recreates Terminal-Bench original-tasks/log-summary (Apache-2.0) on the overlay runner.
# Generated by out/h50/gen_setup.py from the task's files, byte for byte.
mkdir -p /app/logs
cat > /app/logs/app1.log <<'EOF'
2025-08-10 10:00:00 INFO Starting app1 service
2025-08-10 10:00:01 WARNING Low disk space
2025-08-10 10:01:00 ERROR Failed to connect to database
2025-08-10 10:02:00 INFO App1 running smoothly
2025-08-10 10:03:00 ERROR Timeout connecting to cache
EOF
cat > /app/logs/app2.log <<'EOF'
2025-08-10 11:00:00 INFO Starting app2 service
2025-08-10 11:01:00 INFO User login successful
2025-08-10 11:02:00 WARNING Deprecated API call
2025-08-10 11:03:00 ERROR Null pointer exception
2025-08-10 11:04:00 INFO App2 ready
EOF
cat > /app/logs/db.log <<'EOF'
2025-08-10 12:00:00 INFO Database connection established
2025-08-10 12:01:00 WARNING Slow query detected
2025-08-10 12:02:00 ERROR Deadlock detected
2025-08-10 12:03:00 INFO Database maintenance complete
2025-08-10 12:04:00 INFO Backup finished successfully
EOF
