# tb-grid-pattern-transform: recreates Terminal-Bench original-tasks/grid-pattern-transform (Apache-2.0) on the overlay runner.
# Generated by out/h50/gen_setup.py from the task's files, byte for byte.
mkdir -p /app
