# tb-heterogeneous-dates: recreates Terminal-Bench original-tasks/heterogeneous-dates (Apache-2.0) on the overlay runner.
# Generated by out/h50/gen_setup.py from the task's files, byte for byte.
mkdir -p /app
base64 -d <<'EOF' > /app/daily_temp_sf_high.csv
ZGF0ZSx0ZW1wZXJhdHVyZQ0KMjAyNS0wNC0xOSw2NA0KMjAyNS0wNC0yMCw2Mw0KMjAyNS0wNC0y
MSw3MA0KMjAyNS0wNC0yMiw2Ng0KMjAyNS0wNC0yMyw1Nw0KMjAyNS0wNC0yNCw1NQ0KMjAyNS0w
NC0yNSw1Nw==
EOF
base64 -d <<'EOF' > /app/daily_temp_sf_low.csv
ZGF0ZSx0ZW1wZXJhdHVyZQ0KMDQvMTkvMjAyNSAwNjowMDowMCw0OA0KMDQvMjAvMjAyNSAwNjow
MDowMCw1Mg0KMDQtMjMtMjAyNSAwNjowMDowMCw1Mg0KMDQtMjItMjAyNSAwNjowMDowMCw0OA0K
MDQtMjQtMjAyNSAwNjowMDowMCw1Mg0KMDQtMjEtMjAyNSAwNjowMDowMCw0OA0KMDQtMjUtMjAy
NSAwNjowMDowMCw1Mg==
EOF
